# Generated by Django 3.0.4 on 2020-03-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_categories', '0002_auto_20200312_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
